import datetime

# A list of commonly used genres per Discogs (this list is based on Discogs’ popular categories)
GENRES = [
    "Electronic",
    "Pop",
    "Funk / Soul",
    "Jazz",
    "Folk, World, & Country",
    "Classical",
    "Hip Hop",
    "Stage & Screen",
    "Latin",
    "Reggae",
    "Blues",
    "Non-Music",
    "Children's",
    "Brass & Military"
]

# A list of styles common to many genres.
# Note: Styles on Discogs vary by genre, but here is a broad compilation.
STYLES = [
    "Pop Rock",
    "House",
    "Disco",
    "Synth-pop",
    "Soul",
    "Vocal",
    "Alternative Rock",
    "Ballad",
    "Indie Rock",
    "Rock & Roll",
    "Hard Rock",
    "Funk",
    "Folk Rock",
    "Country",
    "Punk",
    "Techno",
    "Classic Rock",
    "Chanson",
    "Experimental",
    "Psychedelic Rock",
    "Soundtrack",
    "Blues Rock",
    "Electro",
    "Folk",
    "Soft Rock",
    "Prog Rock",
    "Downtempo",
    "Romantic",
    "Rhythm & Blues",
    "Easy Listening",
    "New Wave",
    "Heavy Metal",
    "Euro House",
    "Ambient",
    "Hardcore",
    "Schlager",
    "Trance",
    "Deep House",
    "Classical",
    "Contemporary R&B",
    "Country Rock",
    "Swing",
    "Contemporary Jazz",
    "Garage Rock",
    "Europop",
    "Big Band",
    "Tech House",
    "Acoustic",
    "Fusion",
    "Baroque",
    "Dancehall",
    "Black Metal",
    "Modern",
    "Death Metal",
    "Jazz-Funk",
    "Dub",
    "Art Rock",
    "Pop Rap",
    "Garage House",
    "Progressive House",
    "Breakbeat",
    "Minimal",
    "Soul-Jazz",
    "RnB/Swing",
    "Reggae",
    "Drum n Bass",
    "Bop",
    "Thrash",
    "Contemporary",
    "Industrial",
    "Theme",
    "Opera",
    "Glam",
    "Beat",
    "Jazz-Rock",
    "Abstract",
    "Gospel",
    "Score",
    "J-pop",
    "Holiday",
    "Hard Bop",
    "Roots Reggae",
    "Leftfield",
    "Kayōkyoku",
    "Indie Pop",
    "Rockabilly",
    "Avantgarde",
    "Breaks",
    "Post Bop",
    "Latin Jazz",
    "Cool Jazz",
    "Musical",
    "Power Pop",
    "Modern Classical",
    "Dance-pop",
    "Acid",
    "Italo-Disco",
    "Smooth Jazz",
    "Hard Trance",
    "Comedy"
]

# A list of countries – popular ones and additional options.
# This list can be expanded as needed.
COUNTRIES = [
    "United States",
    "United Kingdom",
    "Germany",
    "Italy",
    "Netherlands",
    "Japan",
    "France",
    "Spain",
    "Canada",
    "Greece",
    "Belgium",
    "Australia",
    "Sweden",
    "Denmark",
    "Portugal",
    "Switzerland",
    "Poland",
    "Austria",
    "Finland",
    "Brazil",
    "China",
    "Norway",
    "Hungary",
    "Lithuania",
    "Czech Republic",
    "Argentina",
    "Israel",
    "Mexico",
    "Ukraine",
    "Ireland",
    "Serbia",
    "Indonesia",
    "Croatia",
    "Romania",
    "South Africa",
    "Slovak Republic",
    "Belarus",
    "Northern Ireland",
    "Bulgaria",
    "Turkey",
    "Latvia",
    "Slovenia",
    "Estonia",
    "France (European Territory)",
    "Peru",
    "South Korea",
    "New Zealand",
    "Hong Kong",
    "Chile",
    "Malaysia",
    "Kazakhstan",
    "Colombia",
    "Macedonia",
    "Taiwan",
    "Venezuela",
    "Luxembourg",
    "Bosnia-Herzegovina",
    "Malta",
    "Iceland",
    "United Kingdom (Channel Islands)",
    "Panama",
    "Thailand",
    "Lebanon",
    "Cyprus",
    "El Salvador",
    "Ecuador",
    "Uruguay",
    "Spain (Canary Islands)",
    "Gibraltar",
    "Philippines",
    "Armenia",
    "Guadeloupe (French)",
    "Jamaica",
    "Georgia",
    "San Marino",
    "Morocco",
    "Costa Rica",
    "Bolivia",
    "Vietnam",
    "Trinidad and Tobago",
    "Oman",
    "Monaco",
    "Reunion (French)",
    "Dominican Republic",
    "Paraguay",
    "Moldova, Republic of",
    "New Caledonia (French)",
    "Cayman Islands",
    "Albania",
    "Puerto Rico",
    "Montenegro",
    "Ivory Coast (Cote D'Ivoire)",
    "Uzbekistan",
    "Nigeria",
    "Bahrain",
    "United Arab Emirates",
    "Kenya",
    "Guyana",
    "Guam",
    "Egypt",
    "Tunisia",
    "Uganda",
    "Puerto Rico",
    "Polynesia (French)",
]


# YEARS: Generate a list of years from 1900 up to the current year.
current_year = datetime.datetime.now().year
YEARS = [str(year) for year in range(1900, current_year + 1)]
